[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
messenger = "MeskEHG9jyVQGrZsNSYTLzxH9waE6UjrWEsviCQn2E1"

[programs.devnet]
messenger = "MeskEHG9jyVQGrZsNSYTLzxH9waE6UjrWEsviCQn2E1"

[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
# UIP program
address = "uipby67GWuDDt1jZTWFdXNrsSu83kcxt9r5CLPTKGhX"
[[test.validator.clone]]
# UTS config
address = "oGoTxL4LiedkCW6nW9Wgaqq9gU8EAK5AUL5crhTpucy"
[[test.validator.clone]]
# UTS connector
address = "7sxJfPBs1XPiAVsZDAURmiKKd6LkBZcNMXYqi4aVNKJi"
[[test.validator.clone]]
# Chunk Loader
address = "ChUnQ7H46X5UeQJHVgZFBy3hGM95TwWsmvBRwQxVz3JG"
[[test.validator.account]]
address = "ENRSBZkbQsre1guoPDrpKkTtyaJQuLfCQMgESpjUuVAg"
filename = "tests/accounts/uip-config.json"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test --timeout 0 tests"

get-messages-by-sender = "bun run scripts/getMessagesBySender.ts"
initialize = "bun run scripts/initialize.ts"
send-message = "bun run scripts/sendMessage.ts"
