[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
messenger = "MesRprmcvhQFtyP4xBEsDvCY9ig1ek5Zfwcf26KGZ5f"

[programs.devnet]
messenger = "MesRprmcvhQFtyP4xBEsDvCY9ig1ek5Zfwcf26KGZ5f"

[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
# UIP program
address = "pHoEPVJZRCWYaZ2TjHwVWgeee5DnFWGug7vaMbYt4xe"
[[test.validator.clone]]
# UTS config
address = "J8WXFLwtv6AD45cjbcVtF33EqeVT8Ef9U9iDG8wS4PUH"
[[test.validator.clone]]
# UTS connector
address = "7sxJfPBs1XPiAVsZDAURmiKKd6LkBZcNMXYqi4aVNKJi"
[[test.validator.clone]]
# Chunk Loader
address = "ChUnQ7H46X5UeQJHVgZFBy3hGM95TwWsmvBRwQxVz3JG"
[[test.validator.account]]
address = "C4KbAeFrYCu3LZpUBtGqupArntha1KEdrhz1Nu6pG8Sv"
filename = "tests/accounts/uip-config.json"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test --timeout 0 tests"

get-messages-by-sender = "bun run scripts/getMessagesBySender.ts"
initialize = "bun run scripts/initialize.ts"
send-message = "bun run scripts/sendMessage.ts"
