[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
example-token = "eTokpPEQPZ9Xdt7ZzSoC4pk4bwufdZ6rAEQb3GKchcH"

[programs.devnet]
example-token = "eTokpPEQPZ9Xdt7ZzSoC4pk4bwufdZ6rAEQb3GKchcH"

[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
# UIP program
address = "uipby67GWuDDt1jZTWFdXNrsSu83kcxt9r5CLPTKGhX"
[[test.validator.clone]]
# UTS config
address = "CTspuKSu7eRXzKqtYzR83H5VCZMWVRC4uRLfrA5Cy8WX"
[[test.validator.clone]]
# UTS connector
address = "vAukQz25gyuAHbdzEQS9GxMVZipVFu18MUoayKpETJz"
[[test.validator.account]]
address = "CMFjqmzBd59mHnHZgGz9c1ppZPN8VFnWZ8UtxPVUEJLq"
filename = "tests/accounts/uip_config.json"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test --timeout 0 tests"

bridge = "bun run scripts/bridge.ts"
initialize = "bun run scripts/initialize.ts"
mint = "bun run scripts/mint.ts"
update-admin = "bun run scripts/updateAdmin.ts"
