[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
example-token = "eTokpPEQPZ9Xdt7ZzSoC4pk4bwufdZ6rAEQb3GKchcH"

[programs.devnet]
example-token = "eTokpPEQPZ9Xdt7ZzSoC4pk4bwufdZ6rAEQb3GKchcH"

[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
# UIP program
address = "uipby67GWuDDt1jZTWFdXNrsSu83kcxt9r5CLPTKGhX"
[[test.validator.clone]]
# UTS config
address = "oGoTxL4LiedkCW6nW9Wgaqq9gU8EAK5AUL5crhTpucy"
[[test.validator.clone]]
# UTS connector
address = "7sxJfPBs1XPiAVsZDAURmiKKd6LkBZcNMXYqi4aVNKJi"
[[test.validator.account]]
address = "ENRSBZkbQsre1guoPDrpKkTtyaJQuLfCQMgESpjUuVAg"
filename = "tests/accounts/uip-config.json"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test --timeout 0 tests"

bridge = "bun run scripts/bridge.ts"
initialize = "bun run scripts/initialize.ts"
mint = "bun run scripts/mint.ts"
