[package]
name = "messenger-extension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
borsh = "0.10.4"
messenger = { path = "../../programs/messenger", features = ["no-entrypoint"] }
solana-program = ">=2.0,<2.2"
uip-solana-sdk = "0.1"
